Update DemoToMainMigration.yml

diff --git a/.github/workflows/DemoToMainMigration.yml b/.github/workflows/DemoToMainMigration.yml
--- a/.github/workflows/DemoToMainMigration.yml
+++ b/.github/workflows/DemoToMainMigration.yml
@@ -33,8 +33,9 @@ jobs:
       
       - name: Ensure demo branch is up-to-date
         run: |
-          git checkout -- demo
-          git pull --ff-only origin demo || { echo "Error pulling demo branch"; exit 1; }
+          git fetch origin demo
+          git checkout demo || git checkout -b demo origin/demo
+          git pull --rebase origin demo || { echo "Error pulling demo branch"; exit 1; }
       
       - name: Copy migration files from demo to temporary folder
         run: |
@@ -51,8 +52,8 @@ jobs:
       - name: Checkout main branch
         run: |
           git fetch origin main
-          git checkout -- main || git checkout -b main origin/main
-          git pull --ff-only origin main || { echo "Error pulling main branch"; exit 1; }
+          git checkout main || git checkout -b main origin/main
+          git pull --rebase origin main || { echo "Error pulling main branch"; exit 1; }
       
       - name: Ensure prod/migrations folder exists in main
         run: |
